### ISSUE TITLE
Intall in polar v650

### ISSUE THREAD

**Issue by DayronIG** [pavlinux/Polar.V650.Android#1]
Hello,
How I can install the app in my polar ?

tanks good work

**Comment by pavlinux** [comment]
# adb install Software.apk

**Comment by DayronIG** [comment]
I am trying deploy but the device is in status offline , you can't tell me how can enable the device in android studio
  TNKS

**Comment by pavlinux** [comment]
$ export ANDROID_SERIAL="ABCD123456";
$ adb devices;
